title: Valerie Zhao
email: zhaowanbing911@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Valerie Zhao from School of Physics of Shandong University.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  WanbingZhao # DO NOT include the @ character, or else the build will fail!

avatar: "https://github.com/wanbingzhao/wanbingzhao.github.io/blob/main/wbzhao.jpg"
